package app.drivedelta.data.remote.firestore.dto

import app.drivedelta.data.local.entity.SegmentEntity
import org.junit.Assert.assertEquals
import org.junit.Assert.assertNotEquals
import org.junit.Test

/**
 * Guards the fix for the segment-duplication bug. Segments used to carry an autogenerated `Long`
 * primary key, so `pullAll` rehydrated every one with `id = 0`; Room reads 0 on an autoGenerate key
 * as "assign a fresh one", `OnConflictStrategy.REPLACE` had nothing to match, and each Firestore
 * pull re-inserted the whole set. One real 173 km drive had accumulated 10,236 rows for ~853
 * segments. The id is now derived, which is what makes a pull idempotent.
 */
class SegmentDtoTest {

    private fun dto(tripId: String, index: Int) = SegmentDto(
        tripId = tripId,
        segmentIndex = index,
        roadKey = "Rua A|38.7223,-9.1393|38.7230,-9.1400",
        roadName = "Rua A",
        startLat = 38.7223,
        startLng = -9.1393,
        endLat = 38.7230,
        endLng = -9.1400,
        distanceMeters = 120f,
        durationMs = 8_000L,
        avgSpeedMps = 15f,
        maxSpeedMps = 20f,
    )

    @Test
    fun `id is derived from tripId and segmentIndex`() {
        assertEquals("trip-1#0", SegmentEntity.idFor("trip-1", 0))
        assertEquals("trip-1#7", SegmentEntity.idFor("trip-1", 7))
        assertNotEquals(SegmentEntity.idFor("trip-1", 0), SegmentEntity.idFor("trip-2", 0))
        assertNotEquals(SegmentEntity.idFor("trip-1", 0), SegmentEntity.idFor("trip-1", 1))
    }

    @Test
    fun `pulling the same segment twice yields the same row id`() {
        // Simulates two consecutive pullAll runs over the same remote document.
        val first = dto("trip-1", 3).toEntity(syncedAt = 1_000L)
        val second = dto("trip-1", 3).toEntity(syncedAt = 2_000L)

        assertEquals(first.id, second.id)
        assertEquals("trip-1#3", first.id)
    }

    @Test
    fun `remote id is ignored so documents written by the old build still collapse`() {
        // Older builds keyed the document on a device-local autogenerated number, so the same
        // segment could exist remotely under an arbitrary id. fromMap takes that id but toEntity
        // must re-derive, or the duplicates would survive the upgrade.
        val fromLegacyDoc = SegmentDto.fromMap("41977", dto("trip-1", 3).toMap())

        assertEquals("trip-1#3", fromLegacyDoc.toEntity(syncedAt = 0L).id)
    }

    @Test
    fun `distinct segments of one trip keep distinct ids`() {
        val ids = (0 until 5).map { dto("trip-1", it).toEntity(syncedAt = 0L).id }

        assertEquals(5, ids.toSet().size)
    }
}
