package app.drivedelta.data.remote.firestore

import app.drivedelta.data.local.entity.CarEntity
import app.drivedelta.data.local.entity.EnergyPricesEntity
import app.drivedelta.data.local.entity.FuelLogEntity
import app.drivedelta.data.local.entity.PlaceEntity
import app.drivedelta.data.local.entity.SegmentEntity
import app.drivedelta.data.local.entity.TripEntity
import app.drivedelta.data.remote.firestore.dto.CarDto
import app.drivedelta.data.remote.firestore.dto.EnergyPricesDto
import app.drivedelta.data.remote.firestore.dto.FuelLogDto
import app.drivedelta.data.remote.firestore.dto.PlaceDto
import app.drivedelta.data.remote.firestore.dto.SegmentDto
import app.drivedelta.data.remote.firestore.dto.TripDto
import com.google.firebase.firestore.DocumentReference
import com.google.firebase.firestore.FirebaseFirestore
import com.google.firebase.firestore.Source
import com.google.firebase.firestore.WriteBatch
import kotlinx.coroutines.tasks.await
import javax.inject.Inject
import javax.inject.Singleton

/**
 * All Firestore CRUD for the app's per-user document tree.
 *
 * Every entity is written and read through its DTO as an explicit `Map<String, Any?>` — no Firestore
 * reflection/POJO mapping and no kotlinx serialization — so field names are stable and number
 * coercion is deterministic. The local-only `syncedAt` marker is never written to or read back from
 * Firestore; pulled rows are stamped with the pull timestamp instead.
 *
 * Firestore layout: `/users/{userId}/{collection}/{docId}` where collection is one of `trips`,
 * `segments`, `places`, `cars`, `fuel_logs`.
 */
@Singleton
class FirestoreDataSource @Inject constructor(
    private val firestore: FirebaseFirestore,
) {

    private fun userDoc(userId: String): DocumentReference =
        firestore.collection(USERS).document(userId)

    /** Upserts a trip under its owner's `trips` collection, keyed by [TripEntity.id]. */
    suspend fun pushTrip(trip: TripEntity) {
        userDoc(trip.userId).collection(TRIPS).document(trip.id)
            .set(TripDto.fromEntity(trip).toMap())
            .await()
    }

    /**
     * **Replaces** a trip's remote segments with [segments], deleting any the trip no longer has.
     *
     * Segments live under [userId]'s `segments` collection; [SegmentEntity] carries no `userId` of
     * its own, so the owner is supplied separately. Each document id is [SegmentEntity.id], derived
     * from `tripId`/`segmentIndex` — it used to be a device-local autogenerated number, so the same
     * segment written from two devices (or after a re-process) landed under two documents.
     *
     * Segments are derived data, and re-deriving a drive can produce far fewer of them — the 173 km
     * reference drive went from 853 to 80. Upserting one document at a time leaves the surplus
     * behind, and since a pull replaces the local set with the remote one, the next cold start hands
     * all 853 straight back and silently undoes the recalculation. That is exactly what happened the
     * first time the drives were reprocessed.
     *
     * Stale documents are found by querying `tripId` rather than by assuming an id scheme, because
     * documents written before the id became `tripId#segmentIndex` are keyed on a device-local
     * number that cannot be reconstructed. Writes go in batches — Firestore caps one at 500
     * operations, and a drive under the old algorithm can need nearly twice that.
     */
    suspend fun pushSegmentsForTrip(userId: String, tripId: String, segments: List<SegmentEntity>) {
        val collection = userDoc(userId).collection(SEGMENTS)
        val keep = segments.mapTo(HashSet()) { it.id }
        val stale = collection.whereEqualTo(FIELD_TRIP_ID, tripId).get().await()
            .documents.map { it.reference }.filterNot { it.id in keep }

        val writes = segments.map { segment ->
            { batch: WriteBatch ->
                batch.set(collection.document(segment.id), SegmentDto.fromEntity(segment).toMap())
            }
        } + stale.map { reference -> { batch: WriteBatch -> batch.delete(reference) } }

        writes.chunked(BATCH_LIMIT).forEach { chunk ->
            val batch = firestore.batch()
            chunk.forEach { write -> write(batch) }
            batch.commit().await()
        }
    }

    /**
     * Removes a trip and every segment belonging to it.
     *
     * Deleting a trip locally is not enough. A pull replaces the local set with the remote one, so a
     * trip whose documents survive is handed straight back on the next cold start — the same way a
     * recalculation used to be undone, and for the same reason.
     */
    suspend fun deleteTrip(userId: String, tripId: String) {
        val segments = userDoc(userId).collection(SEGMENTS)
            .whereEqualTo(FIELD_TRIP_ID, tripId).get().await()
            .documents.map { it.reference }

        (segments + userDoc(userId).collection(TRIPS).document(tripId))
            .chunked(BATCH_LIMIT).forEach { chunk ->
                val batch = firestore.batch()
                chunk.forEach { reference -> batch.delete(reference) }
                batch.commit().await()
            }
    }

    /** Upserts a place under its owner's `places` collection, keyed by [PlaceEntity.id]. */
    suspend fun pushPlace(place: PlaceEntity) {
        userDoc(place.userId).collection(PLACES).document(place.id)
            .set(PlaceDto.fromEntity(place).toMap())
            .await()
    }

    /** Removes a place document. Used for the hard delete in F3 (places have no soft-delete). */
    suspend fun deletePlace(userId: String, placeId: String) {
        userDoc(userId).collection(PLACES).document(placeId).delete().await()
    }

    /** Upserts a car under its owner's `cars` collection, keyed by [CarEntity.id]. */
    suspend fun pushCar(car: CarEntity) {
        userDoc(car.userId).collection(CARS).document(car.id)
            .set(CarDto.fromEntity(car).toMap())
            .await()
    }

    /** Upserts a fuel log under its owner's `fuel_logs` collection, keyed by [FuelLogEntity.id]. */
    suspend fun pushFuelLog(log: FuelLogEntity) {
        userDoc(log.userId).collection(FUEL_LOGS).document(log.id)
            .set(FuelLogDto.fromEntity(log).toMap())
            .await()
    }

    /** Upserts the user's energy-pricing settings as the single `settings/energy_prices` document. */
    suspend fun pushEnergyPrices(prices: EnergyPricesEntity) {
        userDoc(prices.userId).collection(SETTINGS).document(EnergyPricesDto.DOC_ID)
            .set(EnergyPricesDto.fromEntity(prices).toMap())
            .await()
    }

    /**
     * Fetches every collection for [userId] and maps each document back to its entity. Pulled rows
     * are marked synced by stamping [syncedAt] (defaults to now) — Firestore is treated as the mirror
     * and the caller merges the snapshot into Room.
     */
    suspend fun pullAll(
        userId: String,
        syncedAt: Long = System.currentTimeMillis(),
    ): RemoteSnapshot {
        val trips = userDoc(userId).collection(TRIPS).get(Source.SERVER).await().documents.map { doc ->
            TripDto.fromMap(doc.id, doc.data ?: emptyMap()).toEntity(syncedAt)
        }
        val segments = userDoc(userId).collection(SEGMENTS).get(Source.SERVER).await().documents.map { doc ->
            SegmentDto.fromMap(doc.id, doc.data ?: emptyMap()).toEntity(syncedAt)
        }
        val places = userDoc(userId).collection(PLACES).get(Source.SERVER).await().documents.map { doc ->
            PlaceDto.fromMap(doc.id, doc.data ?: emptyMap()).toEntity(syncedAt)
        }
        val cars = userDoc(userId).collection(CARS).get(Source.SERVER).await().documents.map { doc ->
            CarDto.fromMap(doc.id, doc.data ?: emptyMap()).toEntity(syncedAt)
        }
        val fuelLogs = userDoc(userId).collection(FUEL_LOGS).get(Source.SERVER).await().documents.map { doc ->
            FuelLogDto.fromMap(doc.id, doc.data ?: emptyMap()).toEntity(syncedAt)
        }
        val energyPrices = userDoc(userId).collection(SETTINGS).document(EnergyPricesDto.DOC_ID)
            .get(Source.SERVER).await()
            .takeIf { it.exists() }
            ?.let { EnergyPricesDto.fromMap(userId, it.data ?: emptyMap()).toEntity(syncedAt) }
        return RemoteSnapshot(
            trips = trips,
            segments = segments,
            places = places,
            cars = cars,
            fuelLogs = fuelLogs,
            energyPrices = energyPrices,
        )
    }

    private companion object {
        const val USERS = "users"
        const val TRIPS = "trips"
        const val SEGMENTS = "segments"
        const val PLACES = "places"
        const val CARS = "cars"
        const val FUEL_LOGS = "fuel_logs"
        const val FIELD_TRIP_ID = "tripId"

        /** Firestore's hard cap is 500 operations per batch; stay clear of it. */
        const val BATCH_LIMIT = 400
        const val SETTINGS = "settings"
    }
}

/**
 * The full set of a user's remote data pulled from Firestore, ready to be merged into Room. Route
 * points are intentionally absent — they are Room-only and never synced.
 */
data class RemoteSnapshot(
    val trips: List<TripEntity>,
    val segments: List<SegmentEntity>,
    val places: List<PlaceEntity>,
    val cars: List<CarEntity>,
    val fuelLogs: List<FuelLogEntity>,
    val energyPrices: EnergyPricesEntity?,
)
