package app.drivedelta.data.remote.firestore.dto

import app.drivedelta.data.local.entity.SegmentEntity
import app.drivedelta.data.remote.firestore.double
import app.drivedelta.data.remote.firestore.float
import app.drivedelta.data.remote.firestore.int
import app.drivedelta.data.remote.firestore.long
import app.drivedelta.data.remote.firestore.string

/**
 * Firestore representation of a [SegmentEntity]. Segments carry no `userId` of their own — they are
 * always nested under the owning user's document, so the owner is supplied out of band by
 * `FirestoreDataSource.pushSegment`. The local Room `id` (autogenerated [Long]) is not part of the
 * wire format; the Firestore document id (a [String]) identifies the segment remotely instead.
 */
data class SegmentDto(
    val tripId: String,
    val segmentIndex: Int,
    val roadKey: String,
    val roadName: String,
    val startLat: Double,
    val startLng: Double,
    val endLat: Double,
    val endLng: Double,
    val distanceMeters: Float,
    val durationMs: Long,
    val avgSpeedMps: Float,
    val maxSpeedMps: Float,
) {

    /** Serializes to a Firestore-friendly primitive map. Floats widen to [Double]. */
    fun toMap(): Map<String, Any?> = mapOf(
        "tripId" to tripId,
        "segmentIndex" to segmentIndex,
        "roadKey" to roadKey,
        "roadName" to roadName,
        "startLat" to startLat,
        "startLng" to startLng,
        "endLat" to endLat,
        "endLng" to endLng,
        "distanceMeters" to distanceMeters.toDouble(),
        "durationMs" to durationMs,
        "avgSpeedMps" to avgSpeedMps.toDouble(),
        "maxSpeedMps" to maxSpeedMps.toDouble(),
    )

    /**
     * Rehydrates a [SegmentEntity]. The Room primary key is left at 0 so Room reassigns it on
     * insert; the remote document id is not mapped back. The [syncedAt] parameter is ignored because
     * [SegmentEntity] has no sync marker column.
     */
    fun toEntity(syncedAt: Long): SegmentEntity = SegmentEntity(
        id = 0,
        tripId = tripId,
        segmentIndex = segmentIndex,
        roadKey = roadKey,
        roadName = roadName,
        startLat = startLat,
        startLng = startLng,
        endLat = endLat,
        endLng = endLng,
        distanceMeters = distanceMeters,
        durationMs = durationMs,
        avgSpeedMps = avgSpeedMps,
        maxSpeedMps = maxSpeedMps,
    )

    companion object {

        fun fromEntity(e: SegmentEntity): SegmentDto = SegmentDto(
            tripId = e.tripId,
            segmentIndex = e.segmentIndex,
            roadKey = e.roadKey,
            roadName = e.roadName,
            startLat = e.startLat,
            startLng = e.startLng,
            endLat = e.endLat,
            endLng = e.endLng,
            distanceMeters = e.distanceMeters,
            durationMs = e.durationMs,
            avgSpeedMps = e.avgSpeedMps,
            maxSpeedMps = e.maxSpeedMps,
        )

        fun fromMap(id: String, m: Map<String, Any?>): SegmentDto = SegmentDto(
            tripId = m.string("tripId"),
            segmentIndex = m.int("segmentIndex"),
            roadKey = m.string("roadKey"),
            roadName = m.string("roadName"),
            startLat = m.double("startLat"),
            startLng = m.double("startLng"),
            endLat = m.double("endLat"),
            endLng = m.double("endLng"),
            distanceMeters = m.float("distanceMeters"),
            durationMs = m.long("durationMs"),
            avgSpeedMps = m.float("avgSpeedMps"),
            maxSpeedMps = m.float("maxSpeedMps"),
        )
    }
}
